// Provider-agnostic summarization function
// Uses Gemini API if GEMINI_API_KEY is set, otherwise falls back to local extractive summarization

interface SummarizeOptions {
  maxLength?: number // Maximum length of summary in sentences
  language?: string  // Language for summary (not implemented in fallback)
}

export async function summarize(
  text: string,
  options: SummarizeOptions = {}
): Promise<string> {
  const { maxLength = 2 } = options

  // Clean the text - remove extra whitespace, HTML tags if any
  const cleanedText = text
    .replace(/<[^>]*>/g, '') // Remove HTML tags
    .replace(/\s+/g, ' ')    // Normalize whitespace
    .trim()

  if (!cleanedText) {
    return ""
  }

  // Check if Gemini API key is available
  const geminiApiKey = process.env.GEMINI_API_KEY

  if (geminiApiKey) {
    try {
      return await summarizeWithGemini(cleanedText, maxLength, geminiApiKey)
    } catch (error) {
      console.warn("Gemini summarization failed, falling back to local summarization:", error)
      // Fall through to local summarization
    }
  }

  // Fallback to local extractive summarization
  return summarizeLocally(cleanedText, maxLength)
}

async function summarizeWithGemini(
  text: string,
  maxLength: number,
  apiKey: string
): Promise<string> {
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`

  const prompt = `Please provide a concise summary of the following email in ${maxLength} sentences or less. Focus on the main points and action items if any:

${text}`

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [{
        parts: [{ text: prompt }]
      }],
      generationConfig: {
        temperature: 0.3,
        maxOutputTokens: 150,
      }
    }),
  })

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.statusText}`)
  }

  const data = await response.json()

  // Extract text from Gemini response
  const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

  if (!generatedText) {
    throw new Error("No text generated by Gemini")
  }

  return generatedText.trim()
}

function summarizeLocally(text: string, maxLength: number): string {
  // Simple extractive summarization: take first N sentences
  // Split by sentence endings (. ! ?) followed by space or end of string
  const sentences = text
    .match(/[^.!?]+[.!?]+/g) || [text]

  // Take first maxLength sentences
  const selectedSentences = sentences.slice(0, maxLength)

  // Join and clean up
  let summary = selectedSentences.join(" ").trim()

  // Ensure it ends with proper punctuation
  if (summary && !/[.!?]$/.test(summary)) {
    summary += "."
  }

  return summary
}

// Cache for summaries to avoid re-summarizing the same email
// In production, you might want to use a proper caching layer
const summaryCache = new Map<string, { summary: string; timestamp: number }>()
const CACHE_TTL = 60 * 60 * 1000 // 1 hour

export async function getCachedSummary(
  emailId: string,
  body: string,
  options: SummarizeOptions = {}
): Promise<string> {
  const cacheKey = `${emailId}:${body.length}`

  // Check cache
  const cached = summaryCache.get(cacheKey)
  if (cached && (Date.now() - cached.timestamp < CACHE_TTL)) {
    return cached.summary
  }

  // Generate new summary
  const summary = await summarize(body, options)

  // Store in cache
  summaryCache.set(cacheKey, {
    summary,
    timestamp: Date.now()
  })

  // Clean old cache entries periodically (simple approach)
  if (summaryCache.size > 1000) {
    // Remove oldest entries
    const entries = Array.from(summaryCache.entries())
    entries.sort((a, b) => a[1].timestamp - b[1].timestamp)
    for (let i = 0; i < Math.floor(entries.length / 2); i++) {
      summaryCache.delete(entries[i][0])
    }
  }

  return summary
}